#!/usr/bin/env python3
"""
ScheML Temporal Training Backend — Fixed-Window Aggregation

Temporal v1 is NOT a sequence model (no LSTM / Transformer).
Instead, it applies fixed-window aggregation over the N most recent events
to produce a tabular feature vector, which is then fed into the standard
FLAML → ONNX pipeline.

This is technically honest: the window transforms time-series data into a
shape that FLAML can handle without sequence-model complexity.  True sequence
models are explicitly out of scope for v1.

Window aggregation:
  For each original feature f and each configured aggregation agg ∈ {mean, sum,
  min, max, last}, a new feature `f__<agg>` is generated by applying agg over
  the window_size most recent timesteps.  The resulting feature vector has
  dimension = len(features) × len(aggregations).

Input dataset format (same as train.py but with window_size and aggregations):
  {
    "X_windows": [[[...step0...], [...step1...], ...], ...],  # shape: (N, W, F)
    "y_train":   [...],
    "y_test":    [...],
    "feature_names": [...],
    "window_size": 5,
    "aggregations": ["mean", "sum", "min", "max", "last"],
    "task_type": "regression" | "binary_classification" | "multiclass_classification",
    "algorithm": "automl" | "linear" | ...,
    "hyperparameters": {}
  }
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List

import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType

# Reuse build helpers from train.py via direct import
sys.path.insert(0, str(Path(__file__).parent))
from train import build_automl_model, build_sklearn_model, camel_to_snake


AGG_FNS = {
    "mean": np.mean,
    "sum":  np.sum,
    "min":  np.min,
    "max":  np.max,
    "last": lambda x, axis: np.take(x, -1, axis=axis),
}


def apply_window_aggregations(
    X_windows: np.ndarray,
    aggregations: List[str],
) -> np.ndarray:
    """
    X_windows: shape (N, W, F)  — N entities, W timesteps, F features
    Returns: shape (N, F * len(aggregations))
    """
    N, W, F = X_windows.shape
    parts = []
    for agg in aggregations:
        fn = AGG_FNS.get(agg)
        if fn is None:
            raise ValueError(f"Unknown aggregation '{agg}'. Supported: {list(AGG_FNS)}")
        result = fn(X_windows, axis=1)  # shape: (N, F)
        parts.append(result)
    return np.concatenate(parts, axis=1).astype(np.float32)


def expand_feature_names(feature_names: List[str], aggregations: List[str]) -> List[str]:
    """Build the expanded feature name list matching the aggregation layout."""
    return [f"{f}__{agg}" for agg in aggregations for f in feature_names]


def evaluate_model(model, X_test, y_test, task_type: str) -> List[Dict[str, Any]]:
    y_pred = model.predict(X_test)
    metrics = []
    if task_type == "regression":
        mse = mean_squared_error(y_test, y_pred)
        metrics += [
            {"metric": "mse",  "value": float(mse),            "split": "test"},
            {"metric": "rmse", "value": float(mse ** 0.5),     "split": "test"},
            {"metric": "mae",  "value": float(mean_absolute_error(y_test, y_pred)), "split": "test"},
            {"metric": "r2",   "value": float(r2_score(y_test, y_pred)),            "split": "test"},
        ]
    else:
        avg = "binary" if task_type == "binary_classification" else "macro"
        metrics += [
            {"metric": "accuracy",  "value": float(accuracy_score(y_test,  y_pred)),              "split": "test"},
            {"metric": "precision", "value": float(precision_score(y_test, y_pred, average=avg, zero_division=0)), "split": "test"},
            {"metric": "recall",    "value": float(recall_score(y_test,    y_pred, average=avg, zero_division=0)), "split": "test"},
            {"metric": "f1",        "value": float(f1_score(y_test,        y_pred, average=avg, zero_division=0)), "split": "test"},
        ]
    return metrics


def main() -> None:
    parser = argparse.ArgumentParser(description="ScheML temporal training backend")
    parser.add_argument("--dataset",    required=True, help="Path to the .dataset.json file")
    parser.add_argument("--output",     required=True, help="Output directory for artifacts")
    parser.add_argument("--model-name", required=True, dest="model_name")
    args = parser.parse_args()

    with open(args.dataset, "r") as f:
        dataset = json.load(f)

    required = {"X_windows", "y_train", "y_test", "feature_names",
                "window_size", "aggregations", "task_type"}
    missing = required - set(dataset.keys())
    if missing:
        raise ValueError(f"Temporal dataset missing keys: {missing}")

    X_windows_raw = np.array(dataset["X_windows"], dtype=np.float32)
    y_raw = np.array(dataset["y_train"] + dataset["y_test"])

    # Split back into train/test
    n_train = len(dataset["y_train"])
    X_windows_train = X_windows_raw[:n_train]
    X_windows_test  = X_windows_raw[n_train:]
    y_train = np.array(dataset["y_train"])
    y_test  = np.array(dataset["y_test"])

    aggregations:   List[str] = dataset["aggregations"]
    feature_names:  List[str] = dataset["feature_names"]
    window_size:    int        = dataset["window_size"]
    task_type:      str        = dataset["task_type"]
    algorithm:      str        = dataset.get("algorithm", "automl")
    hyperparams:    dict       = dataset.get("hyperparameters", {})

    # Apply window aggregation → tabular
    X_train = apply_window_aggregations(X_windows_train, aggregations)
    X_test  = apply_window_aggregations(X_windows_test,  aggregations)
    expanded_names = expand_feature_names(feature_names, aggregations)

    # Train via FLAML (or explicit algorithm)
    if algorithm == "automl":
        model, best_estimator = build_automl_model(task_type, X_train, y_train)
    else:
        model = build_sklearn_model(task_type, algorithm, hyperparams)
        model.fit(X_train, y_train)
        best_estimator = algorithm

    # Evaluate
    metrics = evaluate_model(model, X_test, y_test, task_type)

    # Export to ONNX
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)
    onnx_path = output_dir / f"{args.model_name}.onnx"

    initial_type = [("float_input", FloatTensorType([None, X_train.shape[1]]))]
    onnx_model = convert_sklearn(model, initial_types=initial_type, target_opset=17)
    with open(onnx_path, "wb") as f:
        f.write(onnx_model.SerializeToString())

    # Clean up temp dataset
    try:
        os.remove(args.dataset)
    except OSError:
        pass

    result = {
        "onnxPath": str(onnx_path),
        "metrics": metrics,
        "bestEstimator": best_estimator,
        "windowSize": window_size,
        "aggregations": aggregations,
        "expandedFeatureNames": expanded_names,
    }
    print(json.dumps(result))


if __name__ == "__main__":
    main()
