#!/usr/bin/env node

/**
 * PrisML Generator - reads Prisma annotations and emits TypeScript hints
 */

import { generatorHandler, GeneratorOptions } from '@prisma/generator-helper';
import * as fs from 'fs';
import * as path from 'path';

generatorHandler({
  onManifest() {
    return {
      prettyName: 'PrisML Generator',
      defaultOutput: './generated',
      requiresGenerators: ['prisma-client-js'],
    };
  },
  async onGenerate(options: GeneratorOptions) {
    const outputDir = options.generator.output?.value || './generated';
    
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    const annotations = extractAnnotations(options.dmmf.datamodel);
    const outputPath = path.join(outputDir, 'prisml.schema.ts');
    
    const content = generateSchemaFile(annotations);
    fs.writeFileSync(outputPath, content, 'utf-8');
    
    console.log(`[PrisML Generator] Generated ${outputPath}`);
  },
});

interface FieldAnnotation {
  modelName: string;
  fieldName: string;
  model?: string;
  threshold?: number;
  fallback?: string | boolean | number;
}

function extractAnnotations(datamodel: any): FieldAnnotation[] {
  const annotations: FieldAnnotation[] = [];

  for (const model of datamodel.models || []) {
    for (const field of model.fields || []) {
      if (field.documentation) {
        const match = field.documentation.match(/@prisml:\s*(.+)/);
        if (match) {
          const config = parseAnnotationConfig(match[1]);
          annotations.push({
            modelName: model.name,
            fieldName: field.name,
            ...config,
          });
        }
      }
    }
  }

  return annotations;
}

function parseAnnotationConfig(raw: string): Partial<FieldAnnotation> {
  const config: Partial<FieldAnnotation> = {};
  
  const modelMatch = raw.match(/model="([^"]+)"/);
  if (modelMatch) config.model = modelMatch[1];
  
  const thresholdMatch = raw.match(/threshold=([\d.]+)/);
  if (thresholdMatch) config.threshold = parseFloat(thresholdMatch[1]);
  
  const fallbackMatch = raw.match(/fallback=(\w+|"[^"]+")/);
  if (fallbackMatch) {
    const value = fallbackMatch[1];
    if (value === 'true') config.fallback = true;
    else if (value === 'false') config.fallback = false;
    else if (!isNaN(Number(value))) config.fallback = Number(value);
    else config.fallback = value.replace(/"/g, '');
  }
  
  return config;
}

function generateSchemaFile(annotations: FieldAnnotation[]): string {
  let lines = [
    '/**',
    ' * Auto-generated by prisml-generator',
    ' * Do not edit manually',
    ' */',
    '',
    'export const PrisMLAnnotations = {',
  ];

  for (const annot of annotations) {
    lines.push(`  '${annot.modelName}.${annot.fieldName}': {`);
    if (annot.model) lines.push(`    model: "${annot.model}",`);
    if (annot.threshold !== undefined) lines.push(`    threshold: ${annot.threshold},`);
    if (annot.fallback !== undefined) {
      const val = typeof annot.fallback === 'string' ? `"${annot.fallback}"` : annot.fallback;
      lines.push(`    fallback: ${val},`);
    }
    lines.push(`  },`);
  }

  lines.push('} as const;');
  lines.push('');

  return lines.join('\n');
}
