/**
 * scheml generate command
 * Writes `scheml.d.ts` with trait property augmentation helpers.
 */

import * as fs from 'fs';
import * as path from 'path';
import { Argv } from 'yargs';
import chalk from 'chalk';
import { requireTraitEntityName, resolveConfiguredAdapter } from '../adapterResolution';
import type { AnyTraitDefinition } from '../traitTypes';
import { loadConfigModule, normalizeConfigExports, resolveTraitDefinitions } from './configHelpers';

type GenerateArgs = {
  config: string;
  output: string;
  json?: boolean;
};

function traitValueType(type: AnyTraitDefinition['type']): string {
  switch (type) {
    case 'generative':
      return 'string | null';
    case 'similarity':
      return 'Array<{ id: string; score: number }> | null';
    case 'predictive':
    case 'anomaly':
    case 'temporal':
    default:
      return 'number | string | null';
  }
}

function buildDeclaration(traits: AnyTraitDefinition[], adapterName: string): string {
  const grouped = new Map<string, Array<{ name: string; tsType: string }>>();

  for (const trait of traits) {
    const entityName = requireTraitEntityName(trait, adapterName);
    const list = grouped.get(entityName) ?? [];
    list.push({ name: trait.name, tsType: traitValueType(trait.type) });
    grouped.set(entityName, list);
  }

  const entities = [...grouped.keys()].sort();

  // Universal ScheML namespace helper — works for all adapters.
  const schemlEntityBlocks = entities
    .map((entity) => {
      const fields = (grouped.get(entity) ?? [])
        .sort((a, b) => a.name.localeCompare(b.name))
        .map((f) => `      ${f.name}: ${f.tsType};`)
        .join('\n');
      return `    ${entity}: {\n${fields}\n    };`;
    })
    .join('\n');

  const schemlNamespace = `declare global {\n  namespace ScheML {\n    interface TraitFields {\n${schemlEntityBlocks || '      // no traits discovered'}\n    }\n\n    type EntityName = keyof TraitFields;\n\n    /**\n     * Augment any base type with its materialized trait fields.\n     * @example type CustomerWithTraits = ScheML.WithTraits<'Customer', Customer>;\n     */\n    type WithTraits<TEntityName extends EntityName, TBase> =\n      TBase & TraitFields[TEntityName];\n  }\n}`;

  // Prisma adapter: also emit `declare module '@prisma/client'` augmentation so
  // trait fields appear directly on the generated Prisma model types without
  // requiring the caller to manually wrap with WithTraits<>.
  let prismaAugmentation = '';
  if (adapterName === 'prisma' && entities.length > 0) {
    const modelBlocks = entities
      .map((entity) => {
        const fields = (grouped.get(entity) ?? [])
          .sort((a, b) => a.name.localeCompare(b.name))
          .map((f) => `    ${f.name}?: ${f.tsType};`)
          .join('\n');
        return `  interface ${entity} {\n${fields}\n  }`;
      })
      .join('\n\n');

    prismaAugmentation =
      `/**\n * Prisma client module augmentation — trait fields are added directly\n * to Prisma model types so they appear as optional properties without\n * requiring \`ScheML.WithTraits<>\`.\n */\ndeclare module '@prisma/client' {\n${modelBlocks}\n}\n\n`;
  }

  return `/**\n * AUTO-GENERATED by scheml generate — do not edit manually.\n * Re-run \`scheml generate\` after adding or removing traits.\n */\n\nexport {};\n\n${prismaAugmentation}${schemlNamespace}\n`;
}

export const generateCommand = {
  command: 'generate',
  description: 'Write scheml.d.ts extending adapter entity types with trait properties',
  builder: (yargs: Argv) => {
    return yargs
      .option('config', {
        alias: 'c',
        description: 'Path to scheml.config.ts',
        type: 'string',
        default: './scheml.config.ts',
      })
      .option('output', {
        alias: 'o',
        description: 'Path to generated declaration file',
        type: 'string',
        default: './scheml.d.ts',
      })
      .option('json', {
        description: 'Emit structured JSON',
        type: 'boolean',
        default: false,
      });
  },
  handler: async (argv: GenerateArgs) => {
    const configPath = path.resolve(argv.config);
    const outputPath = path.resolve(argv.output);
    const jsonMode = argv.json as boolean;

    const configModule = await loadConfigModule(configPath);
    const configExports = normalizeConfigExports(configModule);

    const traits = resolveTraitDefinitions(configExports);
    const adapterName = resolveConfiguredAdapter((configExports as { adapter?: unknown }).adapter).name;
    const declaration = buildDeclaration(traits, adapterName);

    fs.writeFileSync(outputPath, declaration, 'utf-8');

    const payload = {
      ok: true,
      outputPath,
      traitCount: traits.length,
    };

    if (jsonMode) {
      process.stdout.write(JSON.stringify(payload) + '\n');
      return;
    }

    console.log(chalk.green('\n[OK] Declaration generated'));
    console.log(chalk.dim(`Path: ${outputPath}`));
    console.log(chalk.dim(`Traits: ${traits.length}`));
  },
};
