/**
 * scheml generate command
 * Writes `scheml.d.ts` with trait property augmentation helpers.
 */

import * as fs from 'fs';
import * as path from 'path';
import { Argv } from 'yargs';
import { createJiti } from 'jiti';
import { pathToFileURL } from 'url';
import chalk from 'chalk';
import type { AnyTraitDefinition } from '../traitTypes';

function isTraitDefinition(value: any): value is AnyTraitDefinition {
  return (
    value &&
    typeof value === 'object' &&
    typeof value.name === 'string' &&
    typeof value.type === 'string' &&
    ['predictive', 'anomaly', 'similarity', 'sequential', 'generative'].includes(value.type)
  );
}

async function loadConfigModule(configPath: string): Promise<Record<string, unknown>> {
  const jiti = createJiti(pathToFileURL(__filename).href, { interopDefault: true });
  return (await jiti.import(configPath)) as Record<string, unknown>;
}

function traitValueType(type: AnyTraitDefinition['type']): string {
  switch (type) {
    case 'generative':
      return 'string | null';
    case 'similarity':
      return 'Array<{ id: string; score: number }> | null';
    case 'predictive':
    case 'anomaly':
    case 'sequential':
    default:
      return 'number | string | null';
  }
}

function buildDeclaration(traits: AnyTraitDefinition[]): string {
  const grouped = new Map<string, Array<{ name: string; tsType: string }>>();

  for (const trait of traits) {
    const entityName = typeof (trait as any).entity === 'string' ? (trait as any).entity : null;
    if (!entityName) continue;
    const list = grouped.get(entityName) ?? [];
    list.push({ name: trait.name, tsType: traitValueType(trait.type) });
    grouped.set(entityName, list);
  }

  const entities = [...grouped.keys()].sort();
  const entityBlocks = entities
    .map((entity) => {
      const fields = (grouped.get(entity) ?? [])
        .sort((a, b) => a.name.localeCompare(b.name))
        .map((f) => `      ${f.name}: ${f.tsType};`)
        .join('\n');
      return `    ${entity}: {\n${fields}\n    };`;
    })
    .join('\n');

  return `/**\n * AUTO-GENERATED by scheml generate\n *\n * This file defines trait property maps you can use to augment ORM entity\n * types in app code with materialized trait fields.\n */\n\nexport {};\n\ndeclare global {\n  namespace ScheML {\n    interface TraitFields {\n${entityBlocks || '      // no traits discovered'}\n    }\n\n    type EntityName = keyof TraitFields;\n\n    type WithTraits<TEntityName extends EntityName, TBase> =\n      TBase & TraitFields[TEntityName];\n  }\n}\n`;
}

export const generateCommand = {
  command: 'generate',
  description: 'Write scheml.d.ts extending ORM types with trait properties',
  builder: (yargs: Argv) => {
    return yargs
      .option('config', {
        alias: 'c',
        description: 'Path to scheml.config.ts',
        type: 'string',
        default: './scheml.config.ts',
      })
      .option('output', {
        alias: 'o',
        description: 'Path to generated declaration file',
        type: 'string',
        default: './scheml.d.ts',
      })
      .option('json', {
        description: 'Emit structured JSON',
        type: 'boolean',
        default: false,
      });
  },
  handler: async (argv: any) => {
    const configPath = path.resolve(argv.config);
    const outputPath = path.resolve(argv.output);
    const jsonMode = argv.json as boolean;

    const configModule = await loadConfigModule(configPath);
    const configExports =
      configModule.default && typeof configModule.default === 'object'
        ? { ...configModule, ...configModule.default }
        : configModule;

    const traits = Object.values(configExports).filter(isTraitDefinition) as AnyTraitDefinition[];
    const declaration = buildDeclaration(traits);

    fs.writeFileSync(outputPath, declaration, 'utf-8');

    const payload = {
      ok: true,
      outputPath,
      traitCount: traits.length,
    };

    if (jsonMode) {
      process.stdout.write(JSON.stringify(payload) + '\n');
      return;
    }

    console.log(chalk.green('\n[OK] Declaration generated'));
    console.log(chalk.dim(`Path: ${outputPath}`));
    console.log(chalk.dim(`Traits: ${traits.length}`));
  },
};
