/**
 * scheml generate command
 * Writes `scheml.d.ts` with trait property augmentation helpers.
 */

import * as fs from 'fs';
import * as path from 'path';
import { Argv } from 'yargs';
import { createJiti } from 'jiti';
import { pathToFileURL } from 'url';
import chalk from 'chalk';
import type { AnyTraitDefinition } from '../traitTypes';

function isTraitDefinition(value: any): value is AnyTraitDefinition {
  return (
    value &&
    typeof value === 'object' &&
    typeof value.name === 'string' &&
    typeof value.type === 'string' &&
    ['predictive', 'anomaly', 'similarity', 'sequential', 'generative'].includes(value.type)
  );
}

async function loadConfigModule(configPath: string): Promise<Record<string, unknown>> {
  const jiti = createJiti(pathToFileURL(__filename).href, { interopDefault: true });
  return (await jiti.import(configPath)) as Record<string, unknown>;
}

function traitValueType(type: AnyTraitDefinition['type']): string {
  switch (type) {
    case 'generative':
      return 'string | null';
    case 'similarity':
      return 'Array<{ id: string; score: number }> | null';
    case 'predictive':
    case 'anomaly':
    case 'sequential':
    default:
      return 'number | string | null';
  }
}

/**
 * Resolves the adapter name from a config export value.
 * Accepts either a string ('prisma') or an adapter object with a `name` field.
 */
function resolveAdapterName(adapter: unknown): string | undefined {
  if (typeof adapter === 'string') return adapter;
  if (adapter && typeof adapter === 'object' && typeof (adapter as any).name === 'string') {
    return (adapter as any).name;
  }
  return undefined;
}

function buildDeclaration(traits: AnyTraitDefinition[], adapterName: string | undefined): string {
  const grouped = new Map<string, Array<{ name: string; tsType: string }>>();

  for (const trait of traits) {
    // Only string-named entities (Prisma/Zod) can be augmented by name.
    // Drizzle traits use a table object as entity and are skipped here.
    const entityName = typeof (trait as any).entity === 'string' ? (trait as any).entity : null;
    if (!entityName) continue;
    const list = grouped.get(entityName) ?? [];
    list.push({ name: trait.name, tsType: traitValueType(trait.type) });
    grouped.set(entityName, list);
  }

  const entities = [...grouped.keys()].sort();

  // Universal ScheML namespace helper — works for all adapters.
  const schemlEntityBlocks = entities
    .map((entity) => {
      const fields = (grouped.get(entity) ?? [])
        .sort((a, b) => a.name.localeCompare(b.name))
        .map((f) => `      ${f.name}: ${f.tsType};`)
        .join('\n');
      return `    ${entity}: {\n${fields}\n    };`;
    })
    .join('\n');

  const schemlNamespace = `declare global {\n  namespace ScheML {\n    interface TraitFields {\n${schemlEntityBlocks || '      // no traits discovered'}\n    }\n\n    type EntityName = keyof TraitFields;\n\n    /**\n     * Augment any base type with its materialized trait fields.\n     * @example type CustomerWithTraits = ScheML.WithTraits<'Customer', Customer>;\n     */\n    type WithTraits<TEntityName extends EntityName, TBase> =\n      TBase & TraitFields[TEntityName];\n  }\n}`;

  // Prisma adapter: also emit `declare module '@prisma/client'` augmentation so
  // trait fields appear directly on the generated Prisma model types without
  // requiring the caller to manually wrap with WithTraits<>.
  let prismaAugmentation = '';
  if (adapterName === 'prisma' && entities.length > 0) {
    const modelBlocks = entities
      .map((entity) => {
        const fields = (grouped.get(entity) ?? [])
          .sort((a, b) => a.name.localeCompare(b.name))
          .map((f) => `    ${f.name}?: ${f.tsType};`)
          .join('\n');
        return `  interface ${entity} {\n${fields}\n  }`;
      })
      .join('\n\n');

    prismaAugmentation =
      `/**\n * Prisma client module augmentation — trait fields are added directly\n * to Prisma model types so they appear as optional properties without\n * requiring \`ScheML.WithTraits<>\`.\n */\ndeclare module '@prisma/client' {\n${modelBlocks}\n}\n\n`;
  }

  return `/**\n * AUTO-GENERATED by scheml generate — do not edit manually.\n * Re-run \`scheml generate\` after adding or removing traits.\n */\n\nexport {};\n\n${prismaAugmentation}${schemlNamespace}\n`;
}

export const generateCommand = {
  command: 'generate',
  description: 'Write scheml.d.ts extending ORM types with trait properties',
  builder: (yargs: Argv) => {
    return yargs
      .option('config', {
        alias: 'c',
        description: 'Path to scheml.config.ts',
        type: 'string',
        default: './scheml.config.ts',
      })
      .option('output', {
        alias: 'o',
        description: 'Path to generated declaration file',
        type: 'string',
        default: './scheml.d.ts',
      })
      .option('json', {
        description: 'Emit structured JSON',
        type: 'boolean',
        default: false,
      });
  },
  handler: async (argv: any) => {
    const configPath = path.resolve(argv.config);
    const outputPath = path.resolve(argv.output);
    const jsonMode = argv.json as boolean;

    const configModule = await loadConfigModule(configPath);
    const configExports =
      configModule.default && typeof configModule.default === 'object'
        ? { ...configModule, ...configModule.default }
        : configModule;

    const traits = Object.values(configExports).filter(isTraitDefinition) as AnyTraitDefinition[];
    const adapterName = resolveAdapterName((configExports as any).adapter);
    const declaration = buildDeclaration(traits, adapterName);

    fs.writeFileSync(outputPath, declaration, 'utf-8');

    const payload = {
      ok: true,
      outputPath,
      traitCount: traits.length,
    };

    if (jsonMode) {
      process.stdout.write(JSON.stringify(payload) + '\n');
      return;
    }

    console.log(chalk.green('\n[OK] Declaration generated'));
    console.log(chalk.dim(`Path: ${outputPath}`));
    console.log(chalk.dim(`Traits: ${traits.length}`));
  },
};
